<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
      <OutputType>Exe</OutputType>
      <TargetFramework>net10.0</TargetFramework>
      <RuntimeIdentifier>win-x64</RuntimeIdentifier>
      <OutputPath>bin/com.tomasz-smigielski.msfs2024connector.sdPlugin</OutputPath>
      <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
      <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
      <SelfContained>true</SelfContained>
      <!-- <PublishSingleFile>true</PublishSingleFile> -->
      <!-- <PublishTrimmed>true</PublishTrimmed> -->
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
   </PropertyGroup>
   <ItemGroup>
      <ProjectReference Include="..\Shared\Shared.csproj" />
   </ItemGroup>
   <ItemGroup>
      <PackageReference Include="StreamDeck-Tools" Version="7.0.0" />
   </ItemGroup>
   <ItemGroup>
      <None Update="manifest.json" CopyToOutputDirectory="PreserveNewest" />
      <None Update="Images/*" CopyToOutputDirectory="PreserveNewest" />
      <None Update="PropertyInspector/*" CopyToOutputDirectory="PreserveNewest" />
   </ItemGroup>
   <Target Name="Pack StreamDeck plugin" AfterTargets="Build">
      <Exec WorkingDirectory="$(TargetDir)" Command="streamdeck pack -f" />
   </Target>
</Project>
