<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
      <OutputType>Exe</OutputType>
      <RuntimeIdentifier>win-x64</RuntimeIdentifier>
      <TargetFramework>net10.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
   </PropertyGroup>
   <ItemGroup>
      <Reference Include="Microsoft.FlightSimulator.SimConnect.dll"/>
      <Reference Include="SimConnect.dll"/>
   </ItemGroup>
   <ItemGroup>
      <ProjectReference Include="..\Shared\Shared.csproj" />
   </ItemGroup>
</Project>
